global:
  scrape_interval: 5s

scrape_configs:

  - job_name: "flask-local"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:5000"]

  - job_name: "pushgateway"
    static_configs:
      - targets: ["pushgateway:9091"]
